# Generated by Django 4.1.6 on 2023-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0010_remove_alert_latitude_remove_alert_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='location',
            new_name='state',
        ),
        migrations.AddField(
            model_name='alert',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
