# Generated by Django 4.1.6 on 2023-02-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_alert_category_alter_alert_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
