# Generated by Django 4.1.6 on 2023-02-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_alter_alert_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='longitude',
        ),
    ]
