# Generated by Django 4.1.6 on 2023-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0011_rename_location_alert_state_alert_lga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='lga',
            field=models.CharField(max_length=100),
        ),
    ]
